---
- name: install required packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - postgresql
    - libpq-dev
    - python3-pip

- name: install psycopg2
  pip:
    name: psycopg2
    state: present

- name: create database "{{ database }}"
  become_user: postgres
  postgresql_db:
    name: "{{ database }}"

- name: create database user "{{ database_user }}"
  become_user: postgres
  postgresql_user:
    db: "{{ database }}"
    name: "{{ database_user }}"
    password: "{{ sql_database_pass }}"
    priv: ALL
