---
- name: install redis-server
  apt:
    name: redis-server
    state: present
    update_cache: yes
  notify: restart redis server

- name: copy redis config
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: root
    mode: 0600
  notify: restart redis server

- name: Flush handlers to restart redis
  meta: flush_handlers