- hosts: ctfd-server
  become: true
  user: root
  roles:
    - name: postresql
      tags: postresql

    - name: redis
      tags: redis

    - name: ctfd
      tags: ctfd

    - name: nginx
      tags: nginx
