---
- name: install mysql-server
  apt:
    update_cache: yes
    state: present
  loop:
    - python3-mysqldb
    - mysql-server

- name: create database "{{ database }}"
  mysql_db:
    name: "{{ database }}"

- name: create database user "{{ database_user }}"
  mysql_user:
    name: "{{ database_user }}"
    priv: "{{ database }}.*:ALL"
    password: "{{ sql_database_pass }}"
