service_user: ctfd
server_path: "/opt/{{ service_user }}"
server_app_path: "/opt/{{ service_user }}/app"

ctfd_repo: https://github.com/CTFd/CTFd
ctfd_version: 2.0.0

venv_path: "{{ server_path }}"
venv_name: ".ctfd_venv"
